### ISSUE TITLE
Global variables filling dynamic memory

### ISSUE THREAD

**Issue by EarlJr53** [sparkfun/SparkFun_BMI270_Arduino_Library#1]
Before integrating this library into my code, I have tried compiling `Example01_BasicReadingsI2C.ino` for my Arduino Mega 2560. When compiling in Arduino IDE, I get an error that the example sketch is using >100% of my Arduino's dynamic memory. I don't see any obviously offending code in the sketch itself, so I am inclined to believe the issue lies in the library itself.

I would love your thoughts on how to get this library to run on my Mega, thank you! Full error message text below.

> Sketch uses 23234 bytes (9%) of program storage space. Maximum is 253952 bytes.
Global variables use 8984 bytes (109%) of dynamic memory, leaving -792 bytes for local variables. Maximum is 8192 bytes.
Not enough memory; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing your footprint.
data section exceeds available space in board
>
> Compilation error: data section exceeds available space in board

**Comment by EarlJr53** [comment]
I notice that the product page on the Sparkfun website seems to show this board being used with an ESP32, which leads me to believe that the library has been optimized for a beefier processor than the Mega.

**Comment by sfe-SparkFro** [comment]
Hi there! This is actually a restriction of the BMI270 itself, not the Arduino library. It requires an 8kB configuration file to be written to it on every power cycle, so that config file needs to be stored on the microcontroller. The underlying [BMI270 API](https://github.com/boschsensortec/BMI270-Sensor-API/tree/master) that this library uses stores it in an array in memory here:

https://github.com/sparkfun/SparkFun_BMI270_Arduino_Library/blob/5b2291b2610bef761a0f30a6271c4a021a4b4164/src/bmi270_api/bmi270.c#L51

In principle, this config file could be stored in the program memory instead of RAM, but that would require modification of the API, which we decided to not do for the sake of forward compatibility (Bosch updates their APIs every once in a while). If you want to take a crack at it for yourself, Arduino has info about it [here](https://www.arduino.cc/reference/en/language/variables/utilities/progmem/).

Hope this helps!

**Comment by EarlJr53** [comment]
@sfe-SparkFro thank you so much for your speedy response! From what I can tell, the [ICM-20948 based 9DoF board](https://www.sparkfun.com/products/15335) looks like it might have what I am looking for. At the very least, if I download its library, it seems to compile successfully. I don't necessarily expect you to be intimately familiar with that other product, but can you think of specific features or functionality that I may lose by switching away from the BMI270 to the ICM-20948?

Thank you again! Is there any way I can commend or officially recognize your helpful response to SparkFun? I really appreciate your willingness to assist me.

**Comment by sfe-SparkFro** [comment]
Sure thing, happy to help!

I've used the ICM-20948 a little bit. I'm not familiar with all the differences, but skimming through its datasheet, there's a few things I can pick out:

The BMI270 has several smart motion detection features (eg. step counting, wrist gestures, motion) and provides an OIS interface (optical image stabalization); the ICM-20948 doesn't have these things. However the ICM-20958 has a built-in magnetometer, and has the FSYNC pin that can be used to synchronize data collection; neither of these are included in the BMI270. Other things appear to be comparable; both are 16-bit resolution, both support I2C and SPI, both have an auxiliary I2C bus, etc. The BMI270 does appear to have a bit less sensor noise as well.

Hope that helps you make an informed decision for your application! If you need more assistance, I'd recommend checking out our [support page](https://www.sparkfun.com/support); you can either contact our support team directly, or even ask in the forums for recommendations. I'm going to close this issue since this is resolved, and we're getting a bit off topic 😉

No need to give any commendations or anything, it's just part of the job 😄 I don't think we actually have a process for that anyways, but I appreciate it!
